# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/red-badger-bot
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: run tests
          command: |
            pipenv run pytest

      - run:
          name: check code formatting
          command: |
            pipenv run black --check .
            pipenv run isort --check-only
            find . -iname "*.py" | xargs pipenv run pylint

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1
